### ISSUE TITLE
RangeError in CesiumJS pops up using 'select area on map'

### ISSUE THREAD

**Issue by emanuelfeld** [NYPL/pic-app#103]
Error pops up over globe graphic. Occurs (sporadically) 'select area on map' chosen, after clicking around on the map several times.

```
An error occurred while rendering. Rendering has stopped.
RangeError: Invalid array length
RangeError: Invalid array length
    at me (http://pic.nypl.org/assets/lib/Cesium/Cesium.js:468:8521)
    at ve (http://pic.nypl.org/assets/lib/Cesium/Cesium.js:468:10706)
    at Ne (http://pic.nypl.org/assets/lib/Cesium/Cesium.js:468:19695)
    at se.render (http://pic.nypl.org/assets/lib/Cesium/Cesium.js:468:24606)
    at A.render (http://pic.nypl.org/assets/lib/Cesium/Cesium.js:474:3041)
    at t (http://pic.nypl.org/assets/lib/Cesium/Cesium.js:473:27061)
```

Running Chrome Version 49.0.2623.87 on El Capitan.

**Comment by mgiraldo** [comment]
yeah that is a very experimental feature… i need to better error-check the rectangle…

**Comment by js2me** [comment]
@emanuelfeld @mgiraldo I have this problem too
I decided to catch this error myself and I short changed Cesium.js code where I will catch this error at `Me`, changed for myself this function
```
function Me(e,t,r,i,n,o,a){
	if(!i){
		debugger;
		console.log('i is not defined',arguments);
	}
	n.length=i || n.length; // <--- this error , so  i is undefined
	for(var s=0;s<i;++s){
		var l,u;o ? 
			(l=Math.min(t-a,e+s*a),
			u=Math.min(t,l+a))
			:
			(l=Math.max(e,Math.pow(r,s)*e),u=Math.min(t,r*l));
		var c = n[s];
		p(c) ? (c.near=l,c.far=u)
			: c = n[s] = new se(l,u)
	}
}
```

**Comment by js2me** [comment]
By the way, I catch this problem very often.
I work with big data , for rendering my data(heating system) I use billboards, pipes(polylines), and simple primitives(circle). Also dynamically render simple polygon buildings and catch error too, but error contains of property `geometry`
